inherit_from: .rubocop_todo.yml

# Layout
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  Exclude:
    - db/schema.rb

Layout/IndentFirstArgument:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - spec/**/*

# Style
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
