version: '3.3'
services:
  web:
    build:
      context: .
    image: web
    environment:
      - DB_HOST=db
    volumes:
      - ${RAILS_VOLUME:-.:/sample_blog}
    networks:
      - sample_blog
    ports:
      - ${RAILS_PUBLISH_PORTS:-3000:3000}
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - sample_blog
    # 本番で使わないので今のところは空けておく
    ports:
      - 15434:5432
volumes:
  db_volume:
networks:
  sample_blog:
