version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - run:
        name: docker-compose build
        command: docker-compose build
    - run:
        name: docker-compose up
        command: docker-compose up -d
    - run:
        name: "before_test: setup db"
        command: docker-compose run web rails db:create db:migrate RAILS_ENV=test
    - run:
        name: test
        command: docker-compose run web rubocop
