#version: 2
#jobs:
#  build:
#    machine:
#      image: circleci/classic:edge
#    steps:
#    - checkout
#    - run:
#        name: build
#        command: docker-compose build
#    - run:
#        name: setup
#        command: |
#          docker-compose run web rails db:create RAILS_ENV=test
#          docker-compose run web rails db:migrate RAILS_ENV=test
#    - run:
#        name: rubocop
#        command: docker-compose run web rubocop

version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-v5-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - cache-v5-{{ arch }}-{{ .Branch }}
        - cache-v5
        paths: ~/caches/images.tar
    - run:
        name: docker load
        command: |
          set +o pipefail
          docker load -i ~/caches/images.tar | true
    - run:
        name: build
        command: docker-compose build
    - run:
        name: docker save
        command: |
          mkdir -p ~/caches
          docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ~/caches/images.tar
    - save_cache:
        key: cache-v5-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths: ~/caches/images.tar
  test:
    machine:
      image: circleci/classic:edge
    steps:
    - checkout
    - restore_cache:
        key: cache-v5-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths: ~/caches/images.tar
    - run:
        name: docker load
        command: |
          set +o pipefail
          docker load -i ~/caches/images.tar | true
    - run:
        name: setup
        command: |
          docker-compose run web rails db:create RAILS_ENV=test
          docker-compose run web rails db:migrate RAILS_ENV=test
    - run:
        name: rubocop
        command: docker-compose run web rubocop
workflows:
  version: 2
  build:
    jobs:
    - build
    - test:
        requires:
        - build
