#version: 2
#jobs:
#  build:
#    machine:
#      image: circleci/classic:edge
#    steps:
#    - checkout
#    - run:
#        name: build
#        command: docker-compose build
#    - run:
#        name: setup
#        command: |
#          docker-compose run web rails db:create RAILS_ENV=test
#          docker-compose run web rails db:migrate RAILS_ENV=test
#    - run:
#        name: rubocop
#        command: docker-compose run web rubocop

version: 2
jobs:
  generate_cache:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: docker-{{ .Branch }}-{{ checksum "docker-compose.yml" }}-{{ checksum "Dockerfile" }}
        paths: ~/caches/images.tar
    - run: docker-compose build
    - run:
        command: |
          mkdir -p ~/caches
          docker save $(docker images -q) -o ~/caches/images.tar
    - save_cache:
        key: docker-{{ .Branch }}-{{ checksum "docker-compose.yml" }}-{{ checksum "Dockerfile" }}
        paths: ~/caches/images.tar
  test:
    machine: true
    # parallelism: 3 # 並列化したいときはparallelismを利用する
    steps:
    - checkout
    - run: pip install docker-compose
    - restore_cache:
        key: docker-{{ .Branch }}-{{ checksum "docker-compose.yml" }}-{{ checksum "Dockerfile" }}
        paths: ~/caches/images.tar
    - run: docker-compose pull # 早い
    - run: docker-compose build # 早い
    - run: docker-compose run web rails db:create RAILS_ENV=test
workflows:
  version: 2
  build:
    jobs:
    - generate_cache
    - test:
        requires:
        - generate_cache
