version: 2
jobs:
  build:
    machine: true
    working_directory: /sample_blog
    steps:
    - checkout
    - run: docker-compose build
    - run: docker-compose run --rm web bin/rails db:create RAILS_ENV=test
    - run: docker-compose run --rm web bin/rails db:migrate RAILS_ENV=test
    - run: docker-compose run --rm web rubocop
